//Our app state is generated by reducer functions, this function always returns an array of books
export default function () { //Create the BooksReducer
  return [
    { title: 'A Song of Ice and Fire'},
    { title: 'The Old And The Sea'},
    { title: 'A Hundred Years of Solitud'},
    { title: 'The Power of Your Subconscious Mind'}
  ];
}
