//Our app state is generated by reducer functions, this function always returns an array of books
export default function () { //Create the BooksReducer
  return [
    { title: 'A Song of Ice and Fire', pages: 873},
    { title: 'The Old And The Sea', pages: 156},
    { title: 'A Hundred Years of Solitud', pages: 102},
    { title: 'The Power of Your Subconscious Mind', pages: 208}
  ];
}
